import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Banner from '../components/Banner'
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'

export default function Home({exploreData,layoutData}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      {/* Banner */}
      <Banner />

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className="pt-6">
          <h2 className='text-4xl font-semibold pb-5'>Explore NearBy</h2>
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
          {exploreData?.map((item,index) => (
            <SmallCard key={index} item={item}/> 
          ))}
          </div>
        </section> 

        <section className='pt-6'>
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
          <div className='flex space-x-3 overflow-x-scroll scrollbar-hide p-3 -ml-3'>
             {layoutData?.map((item,index)=>(
              <MediumCard key={index} item={item} />
             ))}
          </div>
        </section>
        <section>
            <LargeCard  
            img="https://links.papareact.com/4cj"
            title="The Greatest Outdoors"
            description="Wishlists curated by Airbnb"
            buttonText="Get Inspired"
            />
        </section>
      </main>
      <Footer />   
    </div>
  )
}

export async function getStaticProps(){
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(res => res.json());
  const layoutData = await fetch ("https://www.jsonkeeper.com/b/VHHT").then(res => res.json()) 

  return {
    props:{
      exploreData,
      layoutData
    }
  }
}

